Update 3systems branch for testing

diff --git a/deployments/ksqldb/docker-compose.yml b/deployments/ksqldb/docker-compose.yml
--- a/deployments/ksqldb/docker-compose.yml
+++ b/deployments/ksqldb/docker-compose.yml
@@ -53,6 +53,7 @@ services:
       SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
       SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
 
+
   # Create Kafka topics
   kafka-setup:
     image: confluentinc/cp-kafka:latest
@@ -76,10 +77,33 @@ services:
         kafka-topics --create --if-not-exists --topic geofence_control --bootstrap-server broker:29092 --partitions 2 --replication-factor 1 --config retention.ms=-1 &&
 
         kafka-topics --create --if-not-exists --topic robot_geofence_alerts --bootstrap-server broker:29092 --partitions 2 --replication-factor 1 --config retention.ms=3600000 &&
+        kafka-topics --create --if-not-exists --topic speed_control --bootstrap-server broker:29092 --partitions 2 --replication-factor 1 --config retention.ms=-1 &&
 
-        echo 'Topics created successfully.'
+
+
+        kafka-topics --create --if-not-exists --topic sensor_proximity --bootstrap-server broker:29092 --partitions 2 --replication-factor 1 --config retention.ms=-1 &&
+        kafka-topics --create --if-not-exists --topic humidity_control --bootstrap-server broker:29092 --partitions 2 --replication-factor 1 --config retention.ms=-1 &&
+        kafka-topics --create --if-not-exists --topic robot_humidity_alerts --bootstrap-server broker:29092 --partitions 2 --replication-factor 1 --config retention.ms=3600000 &&
+
+        kafka-topics --create --if-not-exists --topic collision_control --bootstrap-server broker:29092 --partitions 1 --replication-factor 1 --config retention.ms=-1 &&
+        kafka-topics --create --if-not-exists --topic robot_collision_alerts --bootstrap-server broker:29092 --partitions 2 --replication-factor 1 --config retention.ms=3600000 &&
+
+
+        kafka-topics --create --if-not-exists --topic robot_registration --bootstrap-server broker:29092 --partitions 2 --replication-factor 1 --config cleanup.policy=compact &&
+        kafka-topics --create --if-not-exists --topic sensor_registration --bootstrap-server broker:29092 --partitions 2 --replication-factor 1 --config cleanup.policy=compact &&
+
+        # SHARD SETUP
+        # 1. Create Compacted Topic
+        #kafka-topics --create --if-not-exists --topic shard_list --bootstrap-server broker:29092 --partitions 1 --replication-factor 1 --config cleanup.policy=compact &&
+        
+        # 2. Seed Data (Using grouped echo to avoid indentation issues)
+        #echo 'Seeding shard_list...' &&
+        #(echo '0:{\"shard_id\":0, \"dummy_link\":1}' && echo '1:{\"shard_id\":1, \"dummy_link\":1}') | kafka-console-producer --bootstrap-server broker:29092 --topic shard_list --property 'parse.key=true' --property 'key.separator=:' &&
+        
+        echo 'Topics created and Shards seeded successfully.'
       "
-  
+  #     kafka-topics --create --if-not-exists --topic geofence_control --bootstrap-server broker:29092 --partitions 2 --replication-factor 1 --config cleanup.policy=compact --config min.cleanable.dirty.ratio=0.01 &&
+
   # ksqlDB Server (Headless Mode)
   ksqldb-server:
     image: confluentinc/ksqldb-server:latest
@@ -102,34 +126,38 @@ services:
       KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
       KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true'
       KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true'
+
       KSQL_KSQL_EXTENSION_DIR: "/opt/ksqldb-udfs"
-      KSQL_CONFIG_FILE: "/etc/ksqldb/ksql-server.properties" #KSQL_KSQL_QUERIES_FILE: "/opt/ksql-setup.sql"
+      KSQL_CONFIG_FILE: "/etc/ksqldb/ksql-server.properties"
+      KSQL_KSQL_QUERIES_FILE: "/opt/ksql-setup.sql" #jeśli interactive zakomentować
     volumes:
       - ./ksql-setup.sql:/opt/ksql-setup.sql
       - ./udf/build/libs/gis-udf-1.0.0.jar:/opt/ksqldb-udfs/gis-udf.jar # - ./ksql-server.properties:/etc/ksqldb/ksql-server.properties
-    healthcheck:
-      test: "curl -f http://localhost:8088/info || exit 1"
-      interval: 10s
-      timeout: 5s
-      retries: 10
+    #jeśli interactive odkomentować healthcheck:
+    #healthcheck:
+    #  test: "curl -f http://localhost:8088/info || exit 1"
+    #  interval: 10s
+    #  timeout: 5s
+    #  retries: 10
 
+  #jeśli interactive odkomentować:
   # ksqlDB setup
-  ksqldb-setup:
-    image: confluentinc/ksqldb-cli:latest
-    container_name: ksqldb-setup
-    depends_on:
-      ksqldb-server:
-        condition: service_healthy
-    volumes:
-      - ./ksql-setup.sql:/opt/ksql-setup.sql
-    command: >
-      bash -c "
-        echo 'Waiting for ksqlDB to be ready...' &&
-        sleep 5 &&
-        echo 'Running ksqlDB setup...' &&
-        ksql http://ksqldb-server:8088 --file /opt/ksql-setup.sql &&
-        echo 'ksqlDB setup complete!'
-      "
+  #ksqldb-setup:
+  #  image: confluentinc/ksqldb-cli:latest
+  #  container_name: ksqldb-setup
+  #  depends_on:
+  #    ksqldb-server:
+  #      condition: service_healthy
+  #  volumes:
+  #    - ./ksql-setup.sql:/opt/ksql-setup.sql
+  #  command: >
+  #    bash -c "
+  #      echo 'Waiting for ksqlDB to be ready...' &&
+  #      sleep 5 &&
+  #      echo 'Running ksqlDB setup...' &&
+  #      ksql http://ksqldb-server:8088 --file /opt/ksql-setup.sql &&
+  #      echo 'ksqlDB setup complete!'
+  #    "
 
 # ros2_bridge service
   ros2_bridge:
@@ -148,6 +176,27 @@ services:
     tty: true
     stdin_open: true
 
+
+
+#  dispatcher:
+#    image: ros2-kafka-dispatcher:local
+#    container_name: kafka_dispatcher
+#    depends_on:
+#      broker:
+#        condition: service_healthy
+#    volumes:
+#      # Keep your bags volume so you can still play data!
+#      - ../bags:/bags
+#    environment:
+#      - ROS_DOMAIN_ID=0
+#    # Launch the dispatcher and point it to your existing broker service
+#    command: >
+#      ros2 launch ros2_kafka_dispatcher_bringup system_minimal.launch.py 
+#      selection_mode:=all 
+#      kafka.bootstrap_servers:=broker:29092
+
+
+
   api:
     build:
       context: .
@@ -157,8 +206,10 @@ services:
     depends_on:
       broker:
         condition: service_healthy
-      ksqldb-setup:
-        condition: service_completed_successfully
+      ksqldb-server: #jeśli interactive zakomentować ksqldb-server
+        condition: service_started
+#      ksqldb-setup: #jeśli interactive odkomentować ksqldb-setup
+#        condition: service_completed_successfully
     ports:
       - "8000:8000"
     environment:
@@ -171,6 +222,24 @@ services:
       - ../bags:/bags
     restart: always
     command: uvicorn app.main:app --host 0.0.0.0 --port 8000
+
+# Collision Detection Service
+  collision-detector:
+    build:
+      context: .
+      dockerfile: Dockerfile.python
+    container_name: collision-detector
+    depends_on:
+      broker:
+        condition: service_healthy
+      kafka-setup:
+        condition: service_completed_successfully
+    volumes:
+      - ./scripts:/scripts
+    environment:
+      KAFKA_BOOTSTRAP_SERVERS: "broker:29092"
+    command: python3 /scripts/collision_detector.py
+    restart: unless-stopped
 
 
   # Python environment for producer and consumers
